### ISSUE TITLE
 assert(self.train_len==len(self.train_file))

### ISSUE THREAD

**Issue by Veranece** [qikunxun/JMRL#1]
作者您好！当我在尝试运行终端语句时，他会提示我    assert(self.train_len==len(self.train_file))，经过我的一些排查之后，我发现是因为dev_train.json文件中的数据项为437，与dev_train_word.npy中的嵌入向量数量对不上，请问是我遗漏了什么吗？感谢您的回复！

**Comment by qikunxun** [comment]
感觉您发现这个问题。这是由于之前上传的prepro_data中数据有缺失，目前我已经在readme上更新了下载链接，感谢您关注我们的工作，谢谢！

**Comment by Veranece** [comment]
好的 感谢您的帮助！
